name: ethereum-wallet-kt-ci

on:
  push: 
    branches:
      - main
  pull_request:
    paths:
      - "implementations/kt/**"

jobs:
  ci:
    name: ethereum-wallet-kt-ci
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and test
        run: ./gradlew build
