name: ethereum-wallet-kt-cd

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - "implementations/kt/**"

jobs:
  cd:
    name: ethereum-wallet-kt-cd
    if: |
      github.event.pull_request.merged &&
      endsWith(github.event.pull_request.title, '/workflows/cd')
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and test
        run: ./gradlew build
        working-directory: ./implementations/kt

      - name: Publish
        run: ./gradlew publish
        env:
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        working-directory: ./implementations/kt