name: swift-metamask-ci

on:
  pull_request:
    paths:
      - "implementations/swift/**"

jobs:
  ci:
    name: swift-metamask-ci
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Pod
        run: pod spec lint --allow-warnings --verbose
